non_used_words = {
    'что',
    'из',
    'как',
    'определить',
    'течет',
    'делать',
    'при',
    'Алиса',
    'алиса',
    }
    
diseases = {
    'эпилепсия': 'diseases/epilepsia.txt',
    'эпилепсии': 'diseases/epilepsia.txt',
    'эпилептический припадок': 'diseases/epilepsia.txt',
    'эпилептическом припадке': 'diseases/epilepsia.txt',
    'эпилепсический припадок': 'diseases/epilepsia.txt',
    'эпилепсическом припадке': 'diseases/epilepsia.txt',
    'инфаркт': 'diseases/heartattack.txt',
    'инфаркте': 'diseases/heartattack.txt',
    'инфаркт миокарда': 'diseases/heartattack.txt',
    'инфаркте миокарда': 'diseases/heartattack.txt',
    'миокард': 'diseases/heartattack.txt',
    'миокарды': 'diseases/heartattack.txt',
    'миокарде': 'diseases/heartattack.txt',
    'миокарда': 'diseases/heartattack.txt',
    'инсульт': 'diseases/insult.txt',
    'инсульте': 'diseases/insult.txt',
    'кровоизлияние в мозг': 'diseases/insult.txt',
    'кровоизлиянии в мозг': 'diseases/insult.txt',
    'внутримозговое кровоизлияние': 'diseases/insult.txt',
    'внутримозговом кровоизлиянии': 'diseases/insult.txt',
    'внутримозговое кровотечение': 'diseases/insult.txt',
    'внутримозговом кровотечении': 'diseases/insult.txt',
    'апоплексический удар': 'diseases/insult.txt',
    'мозговое кровотечение': 'diseases/insult.txt',
    'ожог': 'diseases/burn.txt',
    'ожоге': 'diseases/burn.txt',
    'ожоги': 'diseases/burn.txt',
    'термический ожог': 'diseases/thermal_burn.txt',
    'термическом ожоге': 'diseases/thermal_burn.txt',
    'обгоревшая кожа': 'diseases/thermal_burn.txt',
    'обгоревшей коже': 'diseases/thermal_burn.txt',
    'обуглившаяся кожа': 'diseases/thermal_burn.txt',
    'обуглившейся коже': 'diseases/thermal_burn.txt',
    'кожа обуглилась': 'diseases/thermal_burn.txt',
    'термический': 'diseases/thermal_burn.txt',
    'термическом': 'diseases/thermal_burn.txt',
    'ожог термический': 'diseases/thermal_burn.txt',
    'от воздействия пламени': 'diseases/thermal_burn.txt',
    'воздействие пламени': 'diseases/thermal_burn.txt',
    'ожог от воздействия пламени': 'diseases/thermal_burn.txt',
    'от раскаленных предметов': 'diseases/thermal_burn.txt',
    'раскаленных предметов': 'diseases/thermal_burn.txt',
    'раскаленный предмет': 'diseases/thermal_burn.txt',
    'ожог от раскаленных предметов': 'diseases/thermal_burn.txt',
    'от горячей жидкости': 'diseases/thermal_burn.txt',
    'горячей жидкости': 'diseases/thermal_burn.txt',
    'горячая жидкость': 'diseases/thermal_burn.txt',
    'ожог от горячей жидкости': 'diseases/thermal_burn.txt',
    'от горящей жидкости': 'diseases/thermal_burn.txt',
    'горящей жидкости': 'diseases/thermal_burn.txt',
    'горящая жидкость': 'diseases/thermal_burn.txt',
    'ожог от горящей жидкости': 'diseases/thermal_burn.txt',
    'химические': 'diseases/chemical_burn.txt',
    'химический': 'diseases/chemical_burn.txt',
    'химическом': 'diseases/chemical_burn.txt',
    'химические ожоги': 'diseases/chemical_burn.txt',
    'химический ожог': 'diseases/chemical_burn.txt',
    'химическом ожоге': 'diseases/chemical_burn.txt',
    'ожог химический': 'diseases/chemical_burn.txt',
    'ожог от воздействия кислот': 'diseases/chemical_burn.txt',
    'ожог от воздействия кислоты': 'diseases/chemical_burn.txt',
    'от воздействия кислот': 'diseases/chemical_burn.txt',
    'кислота': 'diseases/chemical_burn.txt',
    'воздействие кислоты': 'diseases/chemical_burn.txt',
    'ожог от воздействия щелочей': 'diseases/chemical_burn.txt',
    'ожог от воздействия щелочи': 'diseases/chemical_burn.txt',
    'от воздействия щелочей': 'diseases/chemical_burn.txt',
    'щелочей': 'diseases/chemical_burn.txt',
    'щелочь': 'diseases/chemical_burn.txt',
    'воздействие щелочи': 'diseases/chemical_burn.txt',
    'ожоги от воздействия солнечных лучей': 'diseases/sunburn.txt',
    'ожоги от воздействия солнца': 'diseases/sunburn.txt',
    'ожог от солнечных лучей': 'diseases/sunburn.txt',
    'ожог от солнца': 'diseases/sunburn.txt',
    'солнечный': 'diseases/sunburn.txt',
    'солнечные': 'diseases/sunburn.txt',
    'солнечный ожог': 'diseases/sunburn.txt',
    'лучевой ожог': 'diseases/sunburn.txt',
    'лучевом ожоге': 'diseases/sunburn.txt',
    'сгоревшая кожа': 'diseases/sunburn.txt',
    'кожа сгорела на солнце': 'diseases/sunburn.txt',
    'электрический ожог': 'diseases/electrical_burn.txt',
    'электрическим током': 'diseases/electrical_burn.txt',
    'током': 'diseases/electrical_burn.txt',
    'ток': 'diseases/electrical_burn.txt',
    'тока': 'diseases/electrical_burn.txt',
    'ожог от электрического тока': 'diseases/electrical_burn.txt',
    'поражение электричсеким током': 'diseases/electrical_burn.txt',
    'электрический': 'diseases/electrical_burn.txt',
    'ожог от электричества': 'diseases/electrical_burn.txt',
    'ожог электричеством': 'diseases/electrical_burn.txt',
    'прекардиальный удар': 'diseases/precordial_stroke.txt',
    'температура': 'diseases/temperature.txt',
    'температуру': 'diseases/temperature.txt',
    'температуры': 'diseases/temperature.txt',
    'температурой': 'diseases/temperature.txt',
    'температуре': 'diseases/temperature.txt',
    'высокая температура': 'diseases/temperature.txt',
    'повышенная температура': 'diseases/temperature.txt',
    'перелом': 'diseases/broken_bones.txt',
    'переломом': 'diseases/broken_bones.txt',
    'переломами': 'diseases/broken_bones.txt',
    'перелома': 'diseases/broken_bones.txt',
    'переломы': 'diseases/broken_bones.txt',
    'открытый перелом': 'diseases/broken_bones.txt',
    'открытые переломы': 'diseases/broken_bones.txt',
    'сломанная кость': 'diseases/broken_bones.txt',
    'сломанна кость': 'diseases/broken_bones.txt',
    'сломанны кости': 'diseases/broken_bones.txt',
    'кость': 'diseases/broken_bones.txt',
    'кости': 'diseases/broken_bones.txt',
    'костью': 'diseases/broken_bones.txt',
    'сломанные кости': 'diseases/broken_bones.txt',
    'паническая атака': 'diseases/panic_attack.txt',
    'паническая': 'diseases/panic_attack.txt',
    'панической': 'diseases/panic_attack.txt',
    'паническим': 'diseases/panic_attack.txt',
    'панических': 'diseases/panic_attack.txt',
    'паника': 'diseases/panic_attack.txt',
    'паники': 'diseases/panic_attack.txt',
    'атака': 'diseases/panic_attack.txt',
    'атаке': 'diseases/panic_attack.txt',
    'кровотечение': 'diseases/bleeding.txt',
    'кровь': 'diseases/bleeding.txt',
    'кровью': 'diseases/bleeding.txt',
    'крови': 'diseases/bleeding.txt',
    'кровотечения': 'diseases/bleeding.txt',
    'кровотечению': 'diseases/bleeding.txt',
    'тошнота': 'diseases/diseases/nausea.txt',
    'помощь': 'services/help.txt',
    'умеешь': 'services/what_you_can_do.txt',
    'можешь': 'services/what_you_can_do.txt',
    'спасибо': 'services/thanks.txt',
    'благодарю': 'services/thanks.txt',
    }
